#!/usr/bin/env node
/*▄────────▄
  █        █
  █  Ядро  █
  █        █
  ▀────────▀*/
require('mvc');

/*▄───────▄
  █       █
  █  MVC  █
  █       █
  ▀───────▀*/
// Коллекция текстов
require('./app/texts/text');

// Коллекция моделей
require('./app/models/modelFiles');
require('./app/models/modelNone');

// Коллекция точек входа
require('./app/entrypoints/entrypoint');

/*▄──────────────────────────────▄
  █                              █
  █  Список глобальных констант  █
  █                              █
  ▀──────────────────────────────▀*/
$.global = class {
/*┌───────────────┐
  │ Список файлов │
  └───────────────┘*/
    PATH_FILES = {
    //  Откуда копируем    Куда копируем
        'files/start':     'start',
        'files/gitignore': '.gitignore'
    }
};

/*▄───────────────▄
  █               █
  █  Точка входа  █
  █               █
  ▀───────────────▀*/
entrypoint = (args) => {
    _=1
};

class a {
    static 'a:a' = 123
}
_=a['a:a']